language: rust
rust: nightly
os:
  - linux
  - osx
cache: cargo
sudo: false
script:
  - cargo test
  - pushd plugin
  - cargo test
  - popd
  - pushd runner
  - cargo install -f
  - popd
  - pushd examples/example_project
  - cargo mutagen
  - cargo mutagen -- --coverage
