[package]
name = "cargo-mutagen"
version = "0.1.0"
authors = ["Hmvp <github@hmvp.nl>"]
description = "Mutation testing for Rust – Runner"
repository = "https://github.com/llogiq/mutator"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"